name: Deploy to GitHub Pages
on:
  push:
    branches: [ "master" ]  # 监听 master 分支的推送

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # 拉取代码

      - name: Install dependencies
        run: npm install  # 安装依赖

      - name: Build project
        run: npm run build  # 执行构建，生成 dist/ 目录

      - name: Verify build output
        run: ls -R dist/  # 调试：确认 dist/ 目录内容

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # 使用 GitHub 自动生成的 token
          branch: gh-pages  # 部署到 gh-pages 分支
          folder: dist  # 关键修改：指向你的构建输出目录